т9 faq
smerch88/simple-it-news pull request #16
Opened 2023-12-07 20:10 UTC by Mykokola

2023-12-12 06:46 UTC, smerch88 requested changes

2023-12-14 05:11 UTC, Mykokola commented on pbn-1/app/about-us/faq/page.tsx
> +      <h1 className=" text-lg font-normal ">FAQ</h1>
+

2023-12-14 05:21 UTC, Mykokola commented on pbn-1/app/about-us/faq/faq.css
> +details[open]  .arrwoIcon {
+/-

2023-12-14 05:21 UTC, Mykokola commented on pbn-1/app/about-us/faq/page.tsx
> +        <ul className="mb-2 flex flex-row md:mb-4">
+/-

2023-12-14 05:22 UTC, Mykokola commented on pbn-1/app/about-us/faq/page.tsx
> +      <div className="  mt-6 text-base font-semibold">
+

2023-12-14 05:23 UTC, Mykokola commented on pbn-1/app/about-us/faq/page.tsx
> +          <Link className="text-blue " href={'whatsApp'}>
+

2023-12-14 05:37 UTC, Mykokola commented on pbn-1/app/about-us/faq/page.tsx
> +                <DownIcon className="arrwoIcon    absolute  right-0 top-2 h-5 w-5 bg-white  smOnly:top-1  smOnly:h-5 smOnly:w-5" />
+

2023-12-14 22:30 UTC, smerch88 approved these changes

2023-12-14 22:31 UTC, merged